version: 2.1
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
          
  deploy:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Copy across app.yaml config
          command: sh ./app.yaml.sh > ./app.yaml
      - run:
          name: Set up gcloud config
          command: |
            echo $GCLOUD_KEY | base64 --decode | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GCLOUD_ZONE}
      - deploy:
          name: Deploying to App Engine
          command: gcloud app deploy app.yaml

orbs:
  node: circleci/node@3.0.0
          
workflows:
  continuous_integration:
    jobs:
      - test
      - deploy:
          name: deploy-app
          requires: 
             - test

